apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-plan
spec:
  params:
    - name: ARGS
      description: The terraform cli commands to run
      type: array
      default:
        - init
  steps:
    - name: init
      image: "docker.io/hashicorp/terraform:light"
      command:
        - terraform
        - init
    - name: terraform-plan
      image: "docker.io/hashicorp/terraform:light"
      command:
        - terraform
        - plan

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-apply-destroy
spec:
  params:
    - name: ARGS
      description: The terraform cli commands to run
      type: array
      default:
        - init
  steps:
    - name: init
      image: "docker.io/hashicorp/terraform:light"
      command:
        - terraform
        - init
    - name: terraform-apply
      image: "docker.io/hashicorp/terraform:light"
      command:
        - terraform
        - apply
        - "-auto-approve"
    - name: terraform-destroy
      image: "docker.io/hashicorp/terraform:light"
      command:
        - terraform
        - destroy
        - "-auto-approve"

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: terraform-pipeline
spec:
  tasks:
    - name: terraform-plan
      taskRef:
        name: terraform-plan

    - name: terraform-apply-destroy
      taskRef:
        name: terraform-apply-destroy

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-terraform-pipeline
spec:
  pipelineRef:
    name: terraform-pipeline
